### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GSzabados**
Just a minor update and to start a discussion with the developer.

### CODE REVIEW

**Comment by GSzabados** [comment]
Hi @psykokwak-com,

Have you managed to make it work with an ESP8266 and a CC1101?

I have found a few days ago the project with the RPi Zero, and later on your repo with the ESP8266 code.

I am curious that is it working for you already with the ESP as currently it is hard to get a RPi Zero. It is possible but for about 2.5 times what is its real value. And I have a few ESPs laying around to try the project.

I am looking forward to use it with an Anyquest Cyble Basic, which supposed to have RADIAN standard as well.

Best Regards,

Gábor

**Comment by psykokwak-com** [comment]
Hi,
I made this fork to make this code working with an ESP32 and ESP8266.
Right now I cannot test it because I'm waiting to to receive my CC1101 module.
I let you know as soon as I'll get it.

**Comment by GSzabados** [comment]
Thanks for the prompt answer! Cool!

I am a bit away from the meter and will not have a chance to try it in the next 4 weeks time (as being busy with work), but I will definitely will.

I already checked and should have a CC1101 somewhere in my toolbox, as I bought one a year or so ago.
That is something, what I have noticed, it is hard to find as well.
I have a few ESP8266 and ESP32 laying around (I believe I have a spare Wemos D1 Mini.)
I searched for a RPi 0 W, but I couldn't find any for a reasonable price, all for 2x or 2.5x of the real price, at least.

There is a topic on the Home Assistant Community Forum where people looked for a solution for the Cyble meters. I posted there about the Rpi version, you might can find other people there who would be interested about the ESP version.
https://community.home-assistant.io/t/water-meter-reading-integration-with-itron-everblu-cyble-enhanced/358347

**Comment by GSzabados** [comment]
I looked at the pins for the ESP32, and saw that some board hasn't got GPIO0 exposed as a pin, so might need to change GDO0 and GDO2 to GPIO2 and GPIO4.

A reference for the SPI GPIOs would be useful actually, as the ESP32 has total 3 sets, as I can recall, and actually the VSPI pins are the default ones. It took me for a while to find it.
(Of course as you used a Wemos D1 Mini, which has limited pins, that is really not a question which one should be the right SPI pin.)

Have you managed to use it with your meter?

The photo looks good!

**Comment by psykokwak-com** [comment]
From one board to another the SPI mapping of PINs can change. I use the default mapping and it is up to everyone to change the mapping according to their constraints. That said, I recommend using the default mapping.
For GDOx, you can remap to any available pin.

At the moment, I can't communicate with the meter. But the SPI communication works.
I received my CC1101 module Friday evening. So I have to wait until Monday morning for my meter to wake up.
I don't have a radio scanner to check if my CC1101 is on the right frequency.

**Comment by GSzabados** [comment]
> have to wait until Monday morning for my meter to wake up.

Any success today? Have you found where you can adjust the frequency and what step if it is necessary?

**Comment by psykokwak-com** [comment]
Hi,
I didn't have much free time today. I can't communicate with the meter on the standard frequency (433.82Mhz). So I modified the program to test all frequencies (in 2.5kHz steps) between 433.6Mhz and 334.0Mhz. I got a response from the meter between 433.8653 Mhz and 433.8703 Mhz.
Now I have to refine to find the central frequency and finish debugging the reading of the frames. I hope to have a little more free time tomorrow.

**Comment by GSzabados** [comment]
Hi,
Thanks for the update. I still haven't got closer to the meter itself, so maybe in a week or so.
It sounds really good your progress. What do you mean by debugging the reading of the frames? So the meter replied, but the message couldn't be decoded as expected?

**Comment by psykokwak-com** [comment]
Yes. It seems I got something but unreadable. Maybe its something else than the meter.
I have to wait until tomorrow now.

**Comment by psykokwak-com** [comment]
I have some sync timing issue.
As I have no RTL-SDR scanner, I work blind :(

**Comment by GSzabados** [comment]
I have managed to build it finally, and after I wired up the C1101 it has immediately received a reply, but I have serious doubts that is the meter:

15:00:11.280 -> Liters : 1074030207
15:00:11.280 -> Battery (in months) : 1073422000
15:00:11.280 -> Counter : -2146624713

Do you see something similar?

I have changed the year and serial number of the meter and I have the same results as above, so it is definitely not the meter.

Can you share the code how you have found the right frequency? I have looked at the waterfall with my RTLSDR, and I cannot really see what it picks up as an answer. There is only a continuous signal on 432MHz, but nothing else. No response from the meter yet.

**Comment by psykokwak-com** [comment]
Hello,
Unfortunately you don't receive anything. This is garbage related to non initialization of variable.
At the moment I can't get any consistent data.
I'm going through all the code to understand the protocol and try to find why it doesn't work.
But at the moment I don't have a lot of free time (especially at times when the meter is accessible).

**Comment by GSzabados** [comment]
> I didn't have much free time today. I can't communicate with the meter on the standard frequency (433.82Mhz). So I modified the program to test all frequencies (in 2.5kHz steps) between 433.6Mhz and 334.0Mhz. I got a response from the meter between 433.8653 Mhz and 433.8703 Mhz.

Can you share how you did this?

**Comment by GSzabados** [comment]
Never mind. I was too far from the meter. The frequency is good, I can see on the SDR that the meter replies. And now I understand your point about the synchronisation. 
I was running with and without debug. I see the signal quality is good but seems to be no data decoded from the buffer. The `l_byte` variables either 1 or 0 only.

**Comment by Pmachat** [comment]
Hello, 

a priori you are using a  Wemos D1 mini.
Could you tell me what I should write in 
+ cc1101.cpp
// Change these define according to your ESP8266 board
#ifdef ESP8266
#define SPI_CSK  ????? // PIN_SPI_CSK: 5 or 14 or D5
#define SPI_MISO ????? // PIN_SPI_MISO: 6 or 12 or D6
#define SPI_MOSI ????  // PIN_SPI_MOSI : 7 or 13 or D7 
#define SPI_SS   ?????  //PIN_SPI_SS:  16 or 8 or 15 or D8
#endif

+ everblu_meters.h
#define GDO2 ????  //header  13 D3?
#define GDO0 ???? //header  11 D1?

Thanks

**Comment by GSzabados** [comment]
> a priori you are using a Wemos D1 mini.

If you are using a D1 Mini, then you shouldn't change anything in the code there, just connect the wires to the right pin. The D1 Mini has one set of SPI pins exposed and that is the default in the code. For GDO, you can connect any just change the code to the GPIO pin what you used. But if you do the same with the D1 mini as @psykokwak-com, you should just connect to those two pins what is already in the code.

**Comment by GSzabados** [comment]
> try to find why it doesn't work

I am considering that there is an issue how the receiver function is working. It is definitely receiving as the rssi, lqi values look good, but the buffer is just 1 byte long, what makes me thing that it is not receiving anything at the end. Or nothing is passed to the code? I have no clue, at the moment, but changing delays or buffer time lengths doesn't change even a bit on the result.

**Comment by psykokwak-com** [comment]
Hi all,
I'm pretty sure there is something wrong with the delay() in the receiving code receive_radian_frame().
Something like a bad time synchronization. As the Raspberry delay() function does not handle delay as precisely as the esp8266/32, there must be things to check there.
I have some free time today. I'm going to look at that.

**Comment by GSzabados** [comment]
When I ran with debug `l_byte_in_rx` turns to be 1 only and that's it, no real length.

And then `l_total_byte` stays 0.

I do not fully understand the logic of this:
```

delay(30); //43ms de bruit
	/*34ms 0101...01  14.25ms 000...000  14ms 1111...11111  83.5ms de data acquitement*/
	if (!receive_radian_frame(0x12,150,rxBuffer,sizeof(rxBuffer))) echo_debug(debug_out,"TMO on REC\r\n");
	delay(30); //50ms de 111111  , mais on a 7+3ms de printf et xxms calculs
	/*34ms 0101...01  14.25ms 000...000  14ms 1111...11111  582ms de data avec l'index */
	rxBuffer_size = receive_radian_frame(0x7C,700,rxBuffer,sizeof(rxBuffer));
	if (rxBuffer_size)
```

Might be due to my French...

**Comment by psykokwak-com** [comment]
Check that link : http://www.lamaisonsimon.fr/wiki/doku.php?id=maison2:compteur_d_eau:compteur_d_eau
It explains the communication frames.

**Comment by GSzabados** [comment]
Can't be that switching the sync pattern to the second one is not working? Or something there because, the first sync pattern works, disregarding that the data is empty. But I think that's what it is intended for.

**Comment by psykokwak-com** [comment]
Yes. I think too.

**Comment by GSzabados** [comment]
`halRfWriteReg(MDMCFG4,0xF8)` is the F8 an intended change there from F6? And why the comment talks about 9.59kbps?

Maybe the order of the commands to the CC1101 matters as well...

Just guessing...

**Comment by psykokwak-com** [comment]
I think there is an oversampling of 4 (2400bit/s * 4 = 9600bit/s) to helps the decode_4bitpbit_serial() function to remove the start and stop bits.

**Comment by GSzabados** [comment]
I am just looking at the manual of the CC1101. The F8 is correct for the 9.6kbps data rate. It is just misleading the 58kHz comment before, as MDMCFG4 does bandwidth and data rate as well by different bits. But it all looks correct.

**Comment by psykokwak-com** [comment]
Ok. I made some progress. Now I'm able to receive the frame from the meter but I have to check if the datas are correctly decoded.

```433.8683 Mhz : FREQ2=0x10 FREQ1=0xAF FREQ0=0xEF 
MARCSTATE : raw:0x13  0x13 free_byte:0x0F sts:0x02 sending 2s WUP...
202 free_byte:0x0E sts:0x07

size_byte=18  l_radian_frame_size_byte=25
GDO0! (0, 0) 1st synch received (1)  rssi=170 lqi=128 F_est=0 
GDO0! (1, 75) TMO on REC

size_byte=124  l_radian_frame_size_byte=171
GDO0! (0, 0) 1st synch received (1)  rssi=170 lqi=184 F_est=255 
GDO0! (1, 100) frame received (689)

Liters : 1040578
Battery (in months) : 100
Counter : 46
Time start : 6
Time end : 18
```

**Edit 1 : I just checked. the data is consistent. It works :)**
**Edit 2 : I'm late for work. Tonight I clean up my code and push to git.**

**Comment by GSzabados** [comment]
That looks good. Where was the issue at the end? Which delay was out of sync?

**Comment by psykokwak-com** [comment]
I just pushed to git.
Let me know if it works :)

**Comment by GSzabados** [comment]
I've literally just opened a few minutes before the repo to have a look and saw that you just pushed the changes. I was just going along how you changed it.
I see that you dropped the delays between the two receive functions, and you changed the way how the receive handles the buffer (omitted one of the ifs). 

Was there anything else, what you think changed the way how it works now? 

What is the story with GDO2? I see that the definition has been removed, and you moved GDO0 to GPIO5. (Actually I did that on Wednesday as well, hoping that is might be the issue, but it hasn't lead to any success.)
Or GDO2 is really not used and can be omitted as well?

**Comment by psykokwak-com** [comment]
Hello,
GDO2 is useless in this case. I simply remove it.
Now I have to understand how to interface this in MQTT with home assistant. I already have an MQTT broker but I don't know anything about home assistant. Does a plugin already exist?

**Comment by GSzabados** [comment]
Create a sensor like this:

```
sensor:
  - platform: mqtt
    state_topic: "BSB-LAN/8700"
    name: BSB-LAN Outside Temperature
    unit_of_measurement: °C
    device_class: temperature
```

**Comment by GSzabados** [comment]
I am just writing the code to the board what I have and came trough an error, as the ESP32 board hasn't got a BUILTIN_LED defined by the IDE. 

So for ESP32 you need to define it manually, if the board has a LED, my board is a Joy-IT ESP32 board and has one at pin 2.

`#define LED_BUILTIN 2`

EDIT: And for convenience the On/Off state are opposite to the ESP8266, On is HIGH, Off is LOW.

**Comment by Pmachat** [comment]
Hello
First of all thank you for your help
I managed to load my Wemos D1-Mini with the sketch.
I see the results on the serial output 😄 
As I am far from my water meter, I think I receive nothing 
I tried to run my wemos without connecting it to the PC to bring it closer to the water meter but it doesn't work. it does not connect to wifi (no ping) 😞 
Do you have any idea what is not working?

Thanks

**Comment by GSzabados** [comment]
> As I am far from my water meter, I think I receive nothing

You might have missed the most important part regarding these meters. They have a programmed working hours, I believe 9 to 17, Monday to Friday. It is the period when a water meter reader person expected to work. So outside of these hours the meter is sleeping and do not reply to any requests. Like during the weekend you will not be able to communicate with the meter.

Regarding Wifi, you should see a message in the serial log once it has been connected to Wifi and to your MQTT broker.

**Comment by GSzabados** [comment]
@psykokwak-com, awesome! finally I managed to make it work. I had to enable to first `delay(30); //43ms de bruit` and now it reads the meter correctly. Before it was just like this:

```
13:41:26.067 -> size_byte=18  l_radian_frame_size_byte=25
13:41:26.067 -> GDO0! (0, 0) 00 1st synch received (1)  rssi=217 lqi=128 F_est=0 
13:41:26.135 -> GDO0! (1, 80) TMO on REC
13:41:26.203 -> 
13:41:26.203 -> size_byte=124  l_radian_frame_size_byte=171
13:41:26.203 -> GDO0! (0, 0) 00 00 1st synch received (2)  rssi=217 lqi=197 F_est=0 
13:41:26.338 -> GDO0! (1, 125) TMO on REC
13:41:26.914 -> Current date (UTC) : 2022/05/30 11:41:28 - 1653910888
13:41:26.914 -> Unable to retrieve data from meter. Retry later...
```

But after enabling that line, boom, all good!

```
13:48:09.453 -> Current date (UTC) : 2022/05/30 11:48:10 - 1653911290
13:48:09.453 -> Liters : 714227
13:48:09.453 -> Battery (in months) : 143
13:48:09.453 -> Counter : 151
13:48:09.453 -> 
```

Tested the trigger as well, that works too! 

Thank you very much making this work!

**Comment by Pmachat** [comment]
> > As I am far from my water meter, I think I receive nothing
> 
> You might have missed the most important part regarding these meters. They have a programmed working hours, I believe 9 to 17, Monday to Friday. It is the period when a water meter reader person expected to work. So outside of these hours the meter is sleeping and do not reply to any requests. Like during the weekend you will not be able to communicate with the meter.
> 
> Regarding Wifi, you should see a message in the serial log once it has been connected to Wifi and to your MQTT broker.

Hello

I'm glad it works for you!

I've tested on friday and today. I have the same message "Unable to retrieve data from meter. Retry later..."
As I am far from my water meter, I think I receive nothing

About wifi,
when my Wemos is connected by usb to the PC, I have the message "Connected to MQTT Broker :)
"
On the other hand, when I connect my wemos only to a power supply, it does not start (?), no connection to wifi, LED flashing.
As I am not connected to the PC, I do not have a serial message

Do you have an idea?

Thanks

**Comment by psykokwak-com** [comment]
Try to start a frequencies scanning. Maybe your CC1101 is not well calibrated (like mine).
I just push a new functionality for Home Assistant.

**Comment by xekil** [comment]
Hello,

Thank you for this project, I haven't received my CC1101 card yet but I started playing with a D1 Mini.

Is it possible to add sensors for home assistant a bit like is the case with ESPhome.

- Wi-Fi signal strength  (sensor, dBm value)
- Connection status      (binary_sensor, value ON or OFF)
- Uptime                       (sensor, value days, hours, minutes, seconds)

Is it also possible to have a little more details on the connections of the CC1101 module (I will receive my cc1101 card next week)

Thanks

**Comment by psykokwak-com** [comment]
Hi @xekil,
I just updated the README to add the pins mapping between the CC1101 and a Wemos D1 board.

**Comment by xekil** [comment]
@psykokwak-com thank you

**Comment by GSzabados** [comment]
@psykokwak-com, after the weekend, I had 3 readings of the meter in a row, in just about a half hour. Do you see the same? It happened 5:54, 6:06 and 6:31.

Might be something with the scheduling when the meter does not reply.

**Comment by psykokwak-com** [comment]
I didn't notice that.
It is scheduled to try every 60 minutes when the read failed and every 24 hours when the read passed.
But I have not yet installed the circuit in its final place.

**Comment by GSzabados** [comment]
I think I know what is going on, I might have triggered the device a few times as a test and they ended queued and now has a "small" jitter only due to the weekend.

The trigger should be handled without the 24h cycle.
What do you think?

**Comment by xekil** [comment]
Hello,

I received my CC1101 module and I managed to detect my counter after doing a frequency scan while being 2 meters from the counter, thank you again for this project :)

I would have some suggestions concerning the code, is it possible to add the possibility of flashing the code in WIFI (ArduinoOTA) and to have access to the Debug in WIFI?

Info :

https://www.aranacorp.com/fr/programmer-un-esp8266-via-wifi-avec-lide-arduino-ota/
https://forum.arduino.cc/t/terminal-wifi-pour-esp8266-esp32/643876/7
https://github.com/bricoleau/WiFiTerm

I tried to merge the codes but without success, it's the first time I use Arduino IDE.

It would be perfect to be able to debug remotely.

**Comment by psykokwak-com** [comment]
Hello @xekil, I just added the ArduinoOTA library support.

**Comment by GSzabados** [comment]
@psykokwak-com, I was just to report back about the multiple readings after the weekend. I though, I have solved it, but unfortunately not.

This morning the count went from 176 to 180.

Is it possible that if the device is power cycled the counters are not cleared and they are still scheduled for 24 hours?

**Comment by psykokwak-com** [comment]
Hi,
I just push some modifications.

**Comment by xekil** [comment]
> Hello @xekil, I just added the ArduinoOTA library support.

Thank you I will test this tomorrow, is it possible to add an OTA password?

`ArduinoOTA.setPassword("my_password")`

https://www.fais-le-toi-meme.fr/fr/electronique/tutoriel/esp8266-arduinoota-mise-a-jour-logiciel-esp8266-wifi

Thank you

Ps: can you activate the problems section on github?
It will be easier for the follow-up :)

**Comment by psykokwak-com** [comment]
Issues tab added :)
Feel free to add the OTA password if you need it.

**Comment by xekil** [comment]
Thank you

**Comment by GSzabados** [comment]
> Hi,
> I just push some modifications.

I have figured out what was causing the extra readings with the previous version of the code.

`void onConnectionEstablished() ` had at the end an `onUpdateData()`, so every time when the WiFi connection dropped out, then the code added another reading which was automatically scheduled for 24 hours, then at the weekend all these schedules shifted to the first hour of the day with the 1 hour repeat times due to the none answering meter.

**Comment by Pmachat** [comment]
Hello
I bought a new cc1101 and everything works now. Thanks for your help.
I just have a distance problem. The counter is about 6-7 meters in a manhole.
It works if I'm nearby. Do you think it would be possible to succeed  with a better antenna?

**Comment by GSzabados** [comment]
> The counter is about 6-7 meters in a manhole.

Do you mean 6-7 meters away or that deep? The local company at my place has a normal car (a small VW Polo or similar), and has a magnetic stick up antenna on the top of the car and the console/laptop in the car. My meter is about 1-1.5 meter underground and about 6 meter from the middle of the street. The car with the antenna still can read it without any issues, so the answer is probably yes, just make sure to get the right antenna.

**Comment by Pmachat** [comment]
Hello
My meter is about 1-1.5 meter underground and about 6 meter from my house on the sidewalk of my street.
It works when I'm about 2 meters from the meter
do you have any advice for an antenna? I bought one that did no better than the previous one
Thanks

**Pull request merged**
